name: CI

on:
  pull_request:

jobs:
  lint-and-typecheck:
    name: Lint & Typecheck
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Generate Prisma Client
        run: DATABASE_URL=postgresql://dummy@localhost:5432/dummy pnpm --filter api exec prisma generate

      - name: Run Linting Checks
        run: pnpm lint

      - name: Run Type Checking Checks
        run: DATABASE_URL=postgresql://dummy@localhost:5432/dummy pnpm check-types
